in_mem_book_db = [{'id': 6, 
    'title': 'The Iron Verses', 
    'author': 'Malik Rowe', 
    'publisher': 'Forgeworks Ltd.', 
    'published_date': '2020-01-30', 
    'page_count': 256, 
    'language': 'Italian'
    },
    {'id': 7, 
    'title': 'Azure Ember', 
    'author': 'Naomi Sterling', 
    'publisher': 'Blue Ember Press', 
    'published_date': '2020-08-14', 
    'page_count': 298, 
    'language': 'japanese'},
    {'id': 8, 
    'title': 'Chronicles of Glass', 
    'author': 'Theo Marlowe', 
    'publisher': 'Crystal Words', 
    'published_date': '2021-04-19', 
    'page_count': 310, 
    'language': 'English'},
    {'id': 9, 
    'title': 'The Hollow Compass', 
    'author': 'Isla Drayton', 
    'publisher': 'Maple & Mirror', 
    'published_date': '2022-12-03', 
    'page_count': 265, 
    'language': 'English'
    },
    {'id': 10, 
    'title': 'Silent Orbit', 
    'author': 'Reuben Chase', 
    'publisher': 'NovaScript', 
    'published_date': '2023-05-17', 
    'page_count': 289, 
    'language': 'Mandarin'
    }
]